version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on: [ postgres ]
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - '3000:3000'
